/**
 * The waitlist roster (§1b). The eight premade characters offered around the empty centre slot.
 *
 * This is the app-side source of truth for WHICH characters exist. It deliberately stores only ids
 * and derives every style from styleFromId() — the same function the world uses — so a roster tile,
 * its generated portrait, and the sprite the player actually receives can never disagree.
 *
 * Portraits are committed PNGs generated by `npm run gen:roster` (pipeline/generate-roster-portraits.mjs).
 * They are art only: picking a character still calls createFromPremade(id), which builds the real
 * procedural sprite sheet. If a portrait PNG is missing the tile falls back to the procedural
 * AvatarPreview, so the roster renders with zero keys, zero network, and never a broken slot.
 *
 * KEEP IN SYNC with ROSTER_IDS in pipeline/generate-roster-portraits.mjs (`npm run verify:roster`).
 */
import { styleFromId, type CharStyle } from "@/game/art";

export const ROSTER_IDS = [
  "premade_0",
  "premade_2",
  "premade_5",
  "premade_7",
  "premade_10",
  "premade_111",
  "premade_121",
  "premade_135",
] as const;

/** The empty centre slot. Not a character: the absence of one. */
export const EMPTY_SLOT = "empty" as const;

export interface RosterEntry {
  id: string;
  style: CharStyle;
  /** Committed portrait; falls back to the procedural sprite if it 404s. */
  portrait: string;
  /** Reading order label. Not a name: these are anonymous stand-ins, as in /onboard. */
  label: string;
}

/** Hair silhouette is the only per-premade differentiator the sprite spec exposes, so it doubles as
 *  a lightweight type tag — the same choice /onboard makes, kept identical for continuity. */
function labelFor(style: CharStyle): string {
  return style.hairStyle.charAt(0).toUpperCase() + style.hairStyle.slice(1);
}

export const ROSTER: RosterEntry[] = ROSTER_IDS.map((id) => {
  const style = styleFromId(id);
  return { id, style, portrait: `/assets/roster/${id}.png`, label: labelFor(style) };
});

/**
 * The 3x3 grid, reading order, with the hole in the middle. The centre is index 4 — the only place
 * echo-violet is allowed on this page, and the primary call to action.
 */
export const GRID: (RosterEntry | typeof EMPTY_SLOT)[] = [
  ROSTER[0],
  ROSTER[1],
  ROSTER[2],
  ROSTER[3],
  EMPTY_SLOT,
  ROSTER[4],
  ROSTER[5],
  ROSTER[6],
  ROSTER[7],
];

export const GRID_COLS = 3;
export const EMPTY_INDEX = 4;
