"""Behavioral cloning policy — §9.3.

π_θ(a | s, z) predicts what the user would say/do. Implemented with NO per-user LLM
fine-tuning (§9.9): the policy is the frozen base LLM conditioned on

  (a) a structured persona profile decoded from the latent z (persona.decode_traits),
  (b) the top-k retrieved past behaviors of this user in similar contexts (pgvector /
      in-memory cosine over the behavior index),
  (c) the current context s.

Candidates are generated by the policy and reranked by the reward model r_φ (§9.4) —
Best-of-N reranking, not per-user RL. Returns the chosen action plus a calibration-ready
confidence (the reward-softmax share held by the top candidate).
"""
from __future__ import annotations

from dataclasses import dataclass
import numpy as np

from .config import SETTINGS
from .persona import Posterior, decode_traits
from .reward import RewardModel
from .embeddings import embed
from .llm import complete


@dataclass
class PolicyResult:
    action: str
    confidence: float           # raw policy confidence p (pre-calibration)
    candidates: list[str]
    rewards: list[float]
    rationale: str              # "why it said that" transparency trace (§10)


def build_system_prompt(traits: list[str], retrieved: list[str], context: str) -> str:
    trait_line = ", ".join(traits) if traits else "still forming — stay neutral and natural"
    mem = "\n".join(f"  - {r}" for r in retrieved) if retrieved else "  (none yet)"
    return (
        "You are speaking AS this user — their faithful echo, not an assistant. "
        "Match how they actually talk and decide.\n"
        f"Their persona reads as: {trait_line}.\n"
        f"Things they have said/done in similar moments:\n{mem}\n"
        f"Current situation: {context}\n"
        "Reply in first person as them, briefly and in their voice."
    )


def generate(
    post: Posterior,
    reward: RewardModel,
    context: str,
    user_message: str,
    retrieved: list[str],
    n: int | None = None,
    model: str | None = None,
) -> PolicyResult:
    n = n or SETTINGS.best_of_n
    traits = decode_traits(post)
    system = build_system_prompt(traits, retrieved, context)
    candidates = complete(
        system,
        [{"role": "user", "content": user_message}],
        model=model,
        n=n,
        temperature=1.0,
    )
    # Rerank by the reward model on embedding of (context ⊕ candidate).
    rewards = [reward.reward(embed(f"{context} || {c}")) for c in candidates]
    order = int(np.argmax(rewards))
    # Confidence = softmax share of the top candidate's reward (temperature 1).
    r = np.array(rewards)
    ex = np.exp(r - r.max())
    softmax = ex / ex.sum()
    confidence = float(softmax[order])

    rationale = (
        f"Chose this over {len(candidates) - 1} alternatives. "
        f"Persona: {', '.join(traits) if traits else 'forming'}. "
        f"Reward margin {rewards[order] - float(np.median(rewards)):+.2f}."
    )
    return PolicyResult(candidates[order], confidence, candidates, rewards, rationale)
